### ISSUE TITLE
Troubles with C11

### ISSUE THREAD

**Issue by nhammer514** [FrankensteinVariorum/collationWorkspace#46]
When running the pipeline.sh script in the fv-postCollation repo, I receive this error: 
```
mv: cannot stat 'fMS_box_c56_chapter.xml': No such file or directory
mv: cannot stat 'fMS_box_c57_vol_ii.xml': No such file or directory
mv: cannot stat 'fMS_box_c57_chap.xml': No such file or directory
mv: cannot stat 'subchunked_standoff_Spine/*.xml': No such file or directory
```

**Comment by ebeshero** [comment]
@nhammer514 Thanks: (for reference, this is an error message Nate sees when running the postCollation pipeline on just C11.) One way we can check the latest output of a single collation unit is by locally running it through the postCollation pipeline to see what happens. I'm not sure of this error, so I'm going to try duplicating it on my end. (For diagnostic purposes, we're not pushing the postCollation results--just using it for checking.)

**Comment by ebeshero** [comment]
@nhammer514 Just had a look at C11 collation on my end. Here's something to try to fix at the *very* end. Can you make the last `<note>` in the Thomas edition show up in the last bit of visible text from the chapter, so it's not lined up against empty tags in the other editions?  Here's how it looks now:


```xml
	<app>
		<rdgGrp n="['17—.&#34;']">
			<rdg wit="f1818">17—.”</rdg>
			<rdg wit="fThomas">17—.”</rdg>
			<rdg wit="f1831">17—.”</rdg>
		</rdgGrp>
		<rdgGrp n="['17—.']">
			<rdg wit="f1823">17—.</rdg>
		</rdgGrp>
	</app>
	<app>
		<rdgGrp n="['&lt;p-end/&gt;']">
			<rdg wit="f1818">&lt;p eID="novel1_letter4_chapter5_div4_div5_p14"/&gt;</rdg>
			<rdg wit="f1823">&lt;p eID="novel1_letter4_chapter5_div4_div5_p14"/&gt;</rdg>
			<rdg wit="fThomas">&lt;p eID="novel1_letter4_chapter5_div4_div5_p13"/&gt;</rdg>
			<rdg wit="f1831">&lt;p eID="novel1_letter4_chapter6_div4_div6_p13"/&gt;</rdg>
		</rdgGrp>
	</app>
	<app>
		<rdgGrp n="['']">
			<rdg wit="f1818"/>
			<rdg wit="f1823"/>
			<rdg wit="f1831"/>
			<rdg wit="fMS">&lt;anchor xml:id="c56-0064.05"/&gt;</rdg>
		</rdgGrp>
		<rdgGrp n="['&lt;note&gt;this letter ought to be re-written.&lt;/note&gt;', '']">
			<rdg wit="fThomas">&lt;note resp="#MWS" anchored="yes"&gt;This letter ought to be
				re-written.&lt;/note&gt; </rdg>
		</rdgGrp>
	</app>
```

**Comment by nhammer514** [comment]
When trying to run collate.py for Chunk 11, I receive this error:
```
Welcome to the Frankenstein Collation Station!
Are you working with ONLY ONE collation chunk? Enter [y/n]: y
Enter only the whole number of the chunk between 1 and 33: 11
+-------This starts the XSLT batch pre-processing of the collation chunk C11-------+
mkdir: cannot create directory ‘collationChunks/C11/input’: File exists
+-------This starts the Python processing of the collation chunk C11-------+
The Python3 version is
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.
The Python version is
Python 3.11.4
test:  ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'add_plain_witness', 'add_witness', 'create_from_dict', 'create_from_json']
Traceback (most recent call last):
  File "C:\Users\Nathan\Desktop\Franken-repo\collationWorkspace\python-collation\collate.py", line 356, in <module>
    main()
  File "C:\Users\Nathan\Desktop\Franken-repo\collationWorkspace\python-collation\collate.py", line 340, in main
    print(tokenLists)
  File "C:\Users\Nathan\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u07f6' in position 181207: character maps to <undefined>
```

It is caused likely because of this character: `߶`
